### ISSUE TITLE
Register your own Twitch application

### ISSUE THREAD

**Issue by AlcaDesign** [vaverix/vaverix-twitch-bot#12]
Please register your own Twitch application and get your own client ID.

https://github.com/vaverix/vaverix-twitch-bot/blob/db8c370975c030d2bd40cd4de1146060dbe78c9b/src/main/functions.js#L33

You can get one by creating a Twitch account, logging into [the Twitch developer site](https://dev.twitch.tv/), then open the console and register a new application. This will give you a client ID to replace the above line with.

The benefits of controlling your own Twitch application includes authorizing users and creating client credentials necessary for the current and future Twitch APIs.

**Comment by vaverix** [comment]
Oh, I forgot to change that, it will be fixed in the next release.
